// <auto-generated />
using BohemianHarmonyHub.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BohemianHarmonyHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240207023007_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BohemianHarmonyHub.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("AlbumId");

                    b.HasIndex("BandId");

                    b.ToTable("albums");
                });

            modelBuilder.Entity("BohemianHarmonyHub.Models.Band", b =>
                {
                    b.Property<int>("BandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BandBiography")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("BandId");

                    b.ToTable("bands");
                });

            modelBuilder.Entity("BohemianHarmonyHub.Models.BandMember", b =>
                {
                    b.Property<int>("BandMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.HasKey("BandMemberId");

                    b.HasIndex("BandId");

                    b.ToTable("bandMembers");
                });

            modelBuilder.Entity("BohemianHarmonyHub.Models.Album", b =>
                {
                    b.HasOne("BohemianHarmonyHub.Models.Band", "Band")
                        .WithMany("Discography")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");
                });

            modelBuilder.Entity("BohemianHarmonyHub.Models.BandMember", b =>
                {
                    b.HasOne("BohemianHarmonyHub.Models.Band", "Band")
                        .WithMany("BandMembers")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");
                });

            modelBuilder.Entity("BohemianHarmonyHub.Models.Band", b =>
                {
                    b.Navigation("BandMembers");

                    b.Navigation("Discography");
                });
#pragma warning restore 612, 618
        }
    }
}
